const $=id=>document.getElementById(id), colors={INOUT:'#3ddbd9',HEIGHT:'#a78bfa'};
let latest=null,playRows=[],playTimer=null,playIndex=0;
const esc=s=>String(s??'--').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
function card(name,p){const cls=p.health>=90?'ok':p.health>=75?'warn':'bad';return `<article class="project"><div class="project-head"><div><p class="eyebrow">TOPIC · ${esc(p.topic)}</p><h2>${name}</h2><span class="status">${esc(p.status)}</span></div><div class="score ${cls}">${p.health}<small>/100</small></div></div><pre class="payload">${esc(p.last_payload?JSON.stringify(p.last_payload,null,2):p.raw_payload)}</pre><div class="metrics"><div class="metric"><small>LAST MESSAGE</small><b>${p.age_s==null?'等待':p.age_s+' s'}</b></div><div class="metric"><small>RECEIVED</small><b>${p.received}</b></div><div class="metric"><small>VALID RATE</small><b>${p.received?(p.valid/p.received*100).toFixed(2):'0.00'}%</b></div></div></article>`}
function draw(projects){const c=$('chart'),dpr=devicePixelRatio||1,w=c.clientWidth,h=240;c.width=w*dpr;c.height=h*dpr;const x=c.getContext('2d');x.scale(dpr,dpr);x.clearRect(0,0,w,h);x.strokeStyle='#203149';x.fillStyle='#8294aa';x.font='11px system-ui';[0,25,50,75,100].forEach(v=>{const y=h-18-v*(h-35)/100;x.beginPath();x.moveTo(34,y);x.lineTo(w,y);x.stroke();x.fillText(v,2,y+3)});Object.entries(projects).forEach(([name,p])=>{const hist=p.history||[];if(!hist.length)return;x.strokeStyle=colors[name];x.lineWidth=3;x.beginPath();hist.forEach((v,i)=>{const px=34+i*Math.max(1,(w-42)/Math.max(1,hist.length-1)),py=h-18-v.health*(h-35)/100;i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke()})}
function render(s){latest=s;$('broker').textContent=s.broker;$('brokerState').textContent=s.broker_connected?'BROKER CONNECTED':'BROKER WAITING';$('total').textContent=Object.values(s.projects).reduce((a,p)=>a+p.received,0).toLocaleString();$('failures').textContent=Object.values(s.projects).reduce((a,p)=>a+p.invalid+p.gaps,0);$('projects').innerHTML=Object.entries(s.projects).map(([n,p])=>card(n,p)).join('');$('stats').innerHTML=`<table><tr><th>PROJECT</th><th>RECEIVED</th><th>VALID</th><th>GAPS</th><th>HEALTH</th></tr>${Object.entries(s.projects).map(([n,p])=>`<tr><td>${n}</td><td>${p.received}</td><td>${p.valid}</td><td>${p.gaps}</td><td>${p.health}/100</td></tr>`).join('')}</table>`;const ev=Object.values(s.projects).flatMap(p=>p.events||[]).reverse();$('events').innerHTML=ev.length?ev.map(e=>`<div class="event"><b>${esc(e.project)} · ${esc(e.type)}</b><br><small>${esc(e.at)} · ${esc(e.severity)}</small></div>`).join(''):'<p>目前沒有故障事件</p>';draw(s.projects)}
async function poll(){try{render(await fetch('/api/state',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json()}))}catch(e){try{const snapshot=await fetch('snapshot.json',{cache:'no-store'}).then(r=>r.json());render(snapshot);$('brokerState').textContent='VERIFIED SNAPSHOT'}catch(_){$('brokerState').textContent='請由 monitor.py 啟動'}}}
function tick(){const n=new Date(),start=latest?new Date(latest.started_at):n,d=Math.max(0,(n-start)/1000),pad=v=>String(Math.floor(v)).padStart(2,'0');$('clock').textContent=n.toLocaleString('zh-TW',{hour12:false});$('duration').textContent=`${pad(d/3600)}:${pad(d%3600/60)}:${pad(d%60)}`}
$('loadHistory').onclick=()=>$('historyFile').click();
$('historyFile').onchange=async e=>{playRows=(await e.target.files[0].text()).trim().split(/\n+/).map(x=>JSON.parse(x)).filter(x=>x.project&&x.payload);playIndex=0;$('playback').disabled=!playRows.length;$('playback').textContent=`▶ 回放 ${playRows.length} 筆`};
$('playback').onclick=()=>{if(playTimer){clearInterval(playTimer);playTimer=null;$('playback').textContent='▶ 繼續回放';return}if(playIndex>=playRows.length)playIndex=0;const replay=JSON.parse(JSON.stringify(latest));Object.values(replay.projects).forEach(p=>{p.received=p.valid=p.invalid=p.gaps=0;p.history=[];p.last_payload=null;p.raw_payload='等待回放資料';p.health=0;p.status='PLAYBACK'});playTimer=setInterval(()=>{const row=playRows[playIndex++],p=replay.projects[row.project];if(p){p.received++;p[row.valid?'valid':'invalid']++;p.last_payload=row.payload;p.raw_payload=row.payload_raw;p.last_received=row.received_at;p.age_s=0;p.health=Math.round(p.valid/p.received*100);p.status='PLAYBACK';p.history.push({t:row.received_at,health:p.health})}render(replay);$('brokerState').textContent=`PLAYBACK ${playIndex}/${playRows.length}`;if(playIndex>=playRows.length){clearInterval(playTimer);playTimer=null;$('playback').textContent='↻ 重新回放'}},100)};
setInterval(poll,1000);setInterval(tick,1000);poll();tick();addEventListener('resize',()=>latest&&draw(latest.projects));
